# Generated by Django 4.2.5 on 2023-09-12 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('force_number', models.CharField(max_length=200, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingUnderInvestigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sno', models.CharField(max_length=200)),
                ('occurence_book_no', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('complainant_name', models.CharField(max_length=200)),
                ('offence', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('case_file', models.ImageField(blank=True, null=True, upload_to='caseFiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('actual_date', models.DateField()),
                ('suspect_name', models.CharField(max_length=200)),
                ('investigating_officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PUILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('hearing', models.BooleanField(default=False)),
                ('mention', models.BooleanField(default=False)),
                ('hearing_mention_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('kase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pendingunderinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='PendingBeforeCourt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sno', models.CharField(max_length=200)),
                ('occurence_book_no', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('complainant_name', models.CharField(max_length=200)),
                ('offence', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('case_file', models.ImageField(blank=True, null=True, upload_to='caseFiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('charge_registry_no', models.CharField(max_length=200)),
                ('court_file_number', models.CharField(max_length=200)),
                ('accused_name', models.CharField(max_length=200)),
                ('hearing_mention_date', models.DateTimeField()),
                ('court', models.CharField(max_length=200)),
                ('investigating_officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PBCLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('hearing', models.BooleanField(default=False)),
                ('mention', models.BooleanField(default=False)),
                ('hearing_mention_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('kase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pendingbeforecourt')),
            ],
        ),
    ]
